name: Tests
on:
  - push
jobs:
  test:
    runs-on: ubuntu-latest # Ubuntu是Linux操作系统，免费开源, 跑 CI/CD 测试，默认选Ubuntu是业界惯例。
    steps:
      - uses: actions/checkout@v3 # 把code checkout到ubuntu虚拟机中
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: | #需要执行多于1行的命令
          python -m pip install --upgrade pip
          pip install pytest-playwright
      - name: Ensure browsers are installed
        run: python -m playwright install chromium --with-deps #把浏览器和需要的dependencies都安装好
      - name: Run Tests
        run: |
          cd cubeit
          python -m http.server 8000 &
          cd ..
          pytest -v
